<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_charge_plan_premium</name>
   <tag></tag>
   <elementGuidId>12d74a49-5be9-4ae8-8d9f-20889234b2e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;AppFrameMain&quot;]/div/div/div/div[2]/div[1]/div[3]/div/div[3]/div/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
